// Generated by https://github.com/wl4g-ai/mcpgen-go

module sonarqube-mcp

go 1.26

require (
	github.com/itchyny/gojq v0.12.19
	github.com/mark3labs/mcp-go v0.48.0
	github.com/prometheus/client_golang v1.20.5
	go.opentelemetry.io/otel v1.28.0
	go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc v1.28.0
	go.opentelemetry.io/otel/exporters/prometheus v0.50.0
	go.opentelemetry.io/otel/sdk v1.28.0
	go.opentelemetry.io/otel/sdk/metric v1.28.0
	gopkg.in/yaml.v3 v3.0.1
)
