// Code generated by https://github.com/flowgent-labs/mcpgen-go
//go:build no_otel

package mcputils

import (
	"net/http"
	"time"
)

// InitMetrics is a no-op when built with -tags no_otel.
func InitMetrics(cfg MetricsConfig) {}

// RecordToolCall is a no-op when built with -tags no_otel.
func RecordToolCall(toolName, toolType, status string, duration time.Duration) {}

// MetricsHandler returns nil when metrics are not compiled in.
func MetricsHandler() http.Handler { return nil }
